version: 2.1
orbs:
    coveralls: coveralls/coveralls@1.0.6
    node: circleci/node@4.9.0
jobs:
    test:
        machine: # executor type
            image: ubuntu-2204:2023.07.2
        working_directory: ~/repo
        jobs:
        steps:
            - checkout
            - run:
                  command: "git submodule init && git submodule update"
                  name: "Setup submodules"
            - node/install:
                  install-yarn: true
                  node-version: "16.13"
            - run:
                  command: "yarn"
                  name: "Install dependencies"
            - run:
                  command: "yarn build"
                  name: "Build project"
workflows:
    tests:
        jobs:
            - test