name: build test

on:
  push:
    branches: [ibadia/library-test]

jobs:
  clone-bluefin-repo:
    name: Checkout tools repo
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          repository: fireflyprotocol/bluefin-exchange-contracts-sui
          token: ${{ secrets.PROD_SUBMODULE_PAT }}
          path: local/sui/submodules/bluefin-exchange-contracts-sui


      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          repository: fireflyprotocol/library-sui
          path: local/sui/submodules/bluefin-exchange-contracts-sui/submodules/library-sui
      - name: List Directory Hierarchy
        run: |
          echo "Current Directory: $PWD"
          echo "Directory Hierarchy:"
          ls -R
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install yarn
        run: npm install -g yarn
      - name: running docker
        working-directory: local/sui
        run: | 
          echo "Current Directory: $PWD"
          docker build --tag sui . &&
          docker container run -p 9000:9000 -p 5003:5003 -p 8084:8084/udp -p 9184:9184 -dit sui
        
      - name: Building library
        working-directory: local/sui/submodules/bluefin-exchange-contracts-sui/submodules/library-sui
        run: |
            npm install -g typescript
            yarn install
            yarn build
      - name: Run Tests
        working-directory: local/sui/submodules/bluefin-exchange-contracts-sui
        run: |
          echo "Current Directory: $PWD" &&
          echo "DEPLOY_ON = cloud" > .env &&
          echo "DEPLOYER_SEED = mixture forest spike snow armor frown enforce busy shove gaze swim term" >> .env &&
          cat .env &&
          yarn install &&
          yarn faucet --account 0x4fc4058ca0162142be16524a794a82f2c184aaa4951b371c8da946541040ea6e &&
          yarn deploy && yarn test


