name: build test

on:
  push:
    branches: [ibadia/library-test]

jobs:
  clone-bluefin-repo:
    name: Checkout tools repo
    runs-on: self-hosted
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          repository: fireflyprotocol/bluefin-exchange-contracts-sui
          token: ${{ secrets.PROD_SUBMODULE_PAT }}
          path: local/sui/submodules/bluefin-exchange-contracts-sui

      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          repository: fireflyprotocol/library-sui
          path: local/sui/submodules/bluefin-exchange-contracts-sui/submodules/library-sui
      - name: List Directory Hierarchy
        needs: [Checkout pull request, Checkout main repository] 
        run: |
          echo "Current Directory: $PWD"
          echo "Directory Hierarchy:"
          ls -R
      - name: Run Tests
        working-directory: local/sui/submodules/bluefin-exchange-contract-sui
        needs: [List Directory Hierarchy]
        run: |
          echo "DEPLOY_ON = cloud" > .env
          echo "DEPLOYER_SEED = mixture forest spike snow armor frown enforce busy shove gaze swim term" >> .env
          cat .env
          yarn install
          yarn build
          yarn faucet --account 0x4fc4058ca0162142be16524a794a82f2c184aaa4951b371c8da946541040ea6e
          yarn deploy


