name: build test

on:
    push:
        branches: [ibadia/library-test]

jobs:
    clone-bluefin-repo:
        - name: Checkout tools repo
            uses: actions/checkout@v3
            with:
                repository: fireflyprotocol/bluefin-exchange-contracts-sui
                path: local/sui/submodules/bluefin-exchange-contracts-sui
        - name: Checkout pull request
            uses: actions/checkout@v3
            with:
                path: local/sui/submodules/bluefin-exchange-contracts-sui/submodules/library-sui
        